##### **Import libraries**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install geopandas
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import re
from datetime import datetime
import numpy as np
#from gmplot import *
import pickle
plt.rcParams['figure.figsize'] = [15, 15]

     |████████████████████████████████| 1.0 MB 5.3 MB/s 
     |████████████████████████████████| 6.3 MB 29.1 MB/s 
     |████████████████████████████████| 15.4 MB 28.5 MB/s 


In [ ]:


[[0.56, 0.34, 0.1 ]]
[[0.57 0.35, 0.08]]
[[0.54 0.36 0.1 ]]
[[0.57 0.34 0.09]]
[[0.59 0.33 0.08]]
[[0.58 0.33 0.09]]
[[0.59 0.29 0.12]]
[[0.53 0.4  0.07]]
[[0.54 0.38 0.08]]

SyntaxError: ignored

In [ ]:
import warnings
warnings.filterwarnings("ignore")

##### **DATA GATHERING**

In [ ]:
# libraries for distance modeling
from shapely.geometry import LineString, MultiPoint, Point
from shapely.ops import nearest_points
from shapely.wkt import loads

In [ ]:
lines_shape_file_path = '/content/drive/MyDrive/data_mining/dataset/2109_STIB_MIVB_Network/ACTU_LINES.shp'
stops_shape_file_path = '/content/drive/MyDrive/data_mining/dataset/2109_STIB_MIVB_Network/ACTU_STOPS.shp'

In [ ]:
stops = gpd.read_file(stops_shape_file_path)
stops.head()

Code_Ligne  Variante  ...       terminus                       geometry
0       012b         1  ...  BRUSSELS CITY  POINT (157950.000 176429.000)
1       012b         1  ...  BRUSSELS CITY  POINT (154334.000 174200.000)
2       012b         1  ...  BRUSSELS CITY  POINT (152934.000 173976.000)
3       012b         1  ...  BRUSSELS CITY  POINT (152428.000 172606.000)
4       012b         1  ...  BRUSSELS CITY  POINT (152045.000 171508.000)

[5 rows x 14 columns]

In [ ]:
temp = pd.DataFrame(stops.groupby(['Code_Ligne','numero_lig','mode']))

In [ ]:
line_info = pd.DataFrame(list(temp[0]),columns = ['LIGNE','numero_lig','mode'])
line_info.head()

LIGNE  numero_lig mode
0  001m           1    M
1  002m           2    M
2  003t           3    T
3  004t           4    T
4  005m           5    M

In [ ]:
lines = gpd.read_file(lines_shape_file_path)
lines.head()

LIGNE  ...                                           geometry
0  001m  ...  LINESTRING Z (146633.500 170956.400 0.000, 146...
1  001m  ...  LINESTRING Z (156746.700 170167.000 0.000, 156...
2  002m  ...  LINESTRING Z (147305.500 172526.900 0.000, 147...
3  002m  ...  LINESTRING Z (147370.500 172498.500 0.000, 147...
4  003t  ...  LINESTRING Z (148550.000 176641.300 0.000, 148...

[5 rows x 6 columns]

In [ ]:
line_geo = lines[lines['VARIANTE']==1]
line_geo.reset_index(inplace=True,drop=True)
line_geo.head()

LIGNE  ...                                           geometry
0  001m  ...  LINESTRING Z (146633.500 170956.400 0.000, 146...
1  002m  ...  LINESTRING Z (147305.500 172526.900 0.000, 147...
2  003t  ...  LINESTRING Z (148550.000 176641.300 0.000, 148...
3  004t  ...  LINESTRING Z (149360.500 172185.100 0.000, 149...
4  005m  ...  LINESTRING Z (142852.600 167202.000 0.000, 142...

[5 rows x 6 columns]

In [ ]:
line_df = pd.merge(line_info,line_geo,on="LIGNE")
line_df.head()

LIGNE  ...                                           geometry
0  001m  ...  LINESTRING Z (146633.500 170956.400 0.000, 146...
1  002m  ...  LINESTRING Z (147305.500 172526.900 0.000, 147...
2  003t  ...  LINESTRING Z (148550.000 176641.300 0.000, 148...
3  004t  ...  LINESTRING Z (149360.500 172185.100 0.000, 149...
4  005m  ...  LINESTRING Z (142852.600 167202.000 0.000, 142...

[5 rows x 8 columns]

In [ ]:
gps_track = pd.read_csv('/content/drive/MyDrive/data_mining/dataset/task4/GPStracks.csv')
gps_track.head()

TrackId        lat       lon                  time
0        1  50.851152  4.345326  2021-11-16T08:35:24Z
1        1  50.851235  4.345191  2021-11-16T08:35:45Z
2        1  50.851328  4.345069  2021-11-16T08:35:48Z
3        1  50.851403  4.344988  2021-11-16T08:35:51Z
4        1  50.851500  4.344920  2021-11-16T08:35:55Z

##### Draw coordinates on google map

In [ ]:
!pip install gmplot
import gmplot
gmap = gmplot.GoogleMapPlotter(50.85045,4.34878, 14,apikey='AIzaSyAY0mkNh_DBbiTnI3BAjUaQNEZaHOOMGfc')

In [ ]:
# draw on single plot
# def draw_line_ids(line_df,gmap):
#     for i in range(len(line_df)):
#         x,y = line_df['geometry'][i].coords.xy
#         lat = list(x)
#         lon = list(y)
#         c = line_df['COLOR_HEX'][i]
#         gmap.scatter(lat, lon, color=c, size=4, marker=False)
#         gmap.plot(lat,lon, color=c,edgewidth=2.5)
#     return gmap
# gmap = draw_line_ids(line_df,gmap)
# gmap.draw("/home/himanshu/line_plots.html" )

In [ ]:
# colors to choose
color=['red', 'orange', 'yellow', 'green', 'blue', 'purple','lime','indigo', 'cyan']

# draw on each plot
for ID, data in gps_track.groupby(["TrackId"]):
    gmap = gmplot.GoogleMapPlotter(50.85045,4.34878, 14,apikey='AIzaSyAY0mkNh_DBbiTnI3BAjUaQNEZaHOOMGfc')    
    lat = list(data['lat'])
    lon = list(data['lon'])
    c = color[ID%len(color)]
    gmap.text(lat[0], lon[0],str(ID),color='black',size =10)
    gmap.text(lat[-1], lon[-1], str(ID),color='black',size = 10)
    gmap.scatter(lat, lon, color=c, size=4, marker=False)
    gmap.plot(lat,lon, color=c,edgewidth=2.5)
    gmap.draw("/home/himanshu/TRACK_PLOTS/"+str(ID)+".html")

##### **STEP 1.  The GPS coordinates follows EPSG:4326 system, and our data is in EPSG:31370 system, so convert lat, lon in belgium coordinate system**

In [ ]:
point_list = []
for i in range(len(gps_track)):
    lon = gps_track['lon'][i]
    lat = gps_track['lat'][i]
    point = Point(lon,lat)
    point_list.append(point)

gps_track['geometry'] = point_list  

In [ ]:
gps_track = gps_track[["TrackId","time","geometry"]]
gps_track.head()

TrackId                  time                             geometry
0        1  2021-11-16T08:35:24Z           POINT (4.345326 50.851152)
1        1  2021-11-16T08:35:45Z  POINT (4.345191000000001 50.851235)
2        1  2021-11-16T08:35:48Z  POINT (4.345069000000001 50.851328)
3        1  2021-11-16T08:35:51Z           POINT (4.344988 50.851403)
4        1  2021-11-16T08:35:55Z              POINT (4.34492 50.8515)

In [ ]:
gps_track_df = gpd.GeoDataFrame(gps_track).set_crs('epsg:4326')
gps_track_df

TrackId                  time                  geometry
0           1  2021-11-16T08:35:24Z  POINT (4.34533 50.85115)
1           1  2021-11-16T08:35:45Z  POINT (4.34519 50.85123)
2           1  2021-11-16T08:35:48Z  POINT (4.34507 50.85133)
3           1  2021-11-16T08:35:51Z  POINT (4.34499 50.85140)
4           1  2021-11-16T08:35:55Z  POINT (4.34492 50.85150)
...       ...                   ...                       ...
1804       11  2021-11-21T12:06:07Z  POINT (4.40454 50.83151)
1805       11  2021-11-21T12:06:08Z  POINT (4.40461 50.83163)
1806       11  2021-11-21T12:06:09Z  POINT (4.40467 50.83174)
1807       11  2021-11-21T12:06:10Z  POINT (4.40474 50.83185)
1808       11  2021-11-21T12:06:11Z  POINT (4.40480 50.83197)

[1809 rows x 3 columns]

In [ ]:
gps_track_transformed = gps_track_df.to_crs(31370)
gps_track_transformed.head()

TrackId                  time                       geometry
0        1  2021-11-16T08:35:24Z  POINT (148350.339 171195.050)
1        1  2021-11-16T08:35:45Z  POINT (148340.836 171204.286)
2        1  2021-11-16T08:35:48Z  POINT (148332.248 171214.634)
3        1  2021-11-16T08:35:51Z  POINT (148326.546 171222.979)
4        1  2021-11-16T08:35:55Z  POINT (148321.761 171233.771)

##### **Step 2. Match the point to the nearest line**

In [ ]:
point_df = pd.DataFrame(gps_track_transformed,columns = ['TrackId','geometry'])
point_df.head()

TrackId                       geometry
0        1  POINT (148350.339 171195.050)
1        1  POINT (148340.836 171204.286)
2        1  POINT (148332.248 171214.634)
3        1  POINT (148326.546 171222.979)
4        1  POINT (148321.761 171233.771)

In [ ]:
gps_track_transformed

TrackId                  time                       geometry
0           1  2021-11-16T08:35:24Z  POINT (148350.339 171195.050)
1           1  2021-11-16T08:35:45Z  POINT (148340.836 171204.286)
2           1  2021-11-16T08:35:48Z  POINT (148332.248 171214.634)
3           1  2021-11-16T08:35:51Z  POINT (148326.546 171222.979)
4           1  2021-11-16T08:35:55Z  POINT (148321.761 171233.771)
...       ...                   ...                            ...
1804       11  2021-11-21T12:06:07Z  POINT (152521.283 169010.671)
1805       11  2021-11-21T12:06:08Z  POINT (152525.997 169023.244)
1806       11  2021-11-21T12:06:09Z  POINT (152530.570 169035.927)
1807       11  2021-11-21T12:06:10Z  POINT (152535.143 169048.722)
1808       11  2021-11-21T12:06:11Z  POINT (152539.434 169061.406)

[1809 rows x 3 columns]

In [ ]:
line_df

LIGNE  ...                                           geometry
0   001m  ...  LINESTRING Z (146633.500 170956.400 0.000, 146...
1   002m  ...  LINESTRING Z (147305.500 172526.900 0.000, 147...
2   003t  ...  LINESTRING Z (148550.000 176641.300 0.000, 148...
3   004t  ...  LINESTRING Z (149360.500 172185.100 0.000, 149...
4   005m  ...  LINESTRING Z (142852.600 167202.000 0.000, 142...
..   ...  ...                                                ...
82  211b  ...  LINESTRING Z (149192.600 170608.700 0.000, 149...
83  212b  ...  LINESTRING Z (149229.000 170664.500 0.000, 149...
84  213b  ...  LINESTRING Z (149192.600 170608.700 0.000, 149...
85  216b  ...  LINESTRING Z (149229.000 170664.500 0.000, 149...
86  218b  ...  LINESTRING Z (149173.500 170683.400 0.000, 149...

[87 rows x 8 columns]

In [ ]:
from IPython.display import display, HTML

In [ ]:
def notmalize_ls(ls):
    ls = np.array(ls)
    normalized_v = ls / np.sqrt(np.sum(ls**2))
    return normalized_v

In [ ]:
closeness_thresh = 20
trip_track= {}
for ID,df in gps_track_transformed.groupby(['TrackId'],sort=False):
    print("Processing trackID ",ID)
    track_id = ID
    
    # get the closest lines for the trip tuple of (count,dist)
    point_line_intersect={}
    
    
    #not closer to any line count
    far_count=0
    
    # iterating over each track id
    for index,data in df.iterrows():
        point = data['geometry']
        prv_dist = 100000
        close_not_found = True
        
        for line_index, line_data in line_df.iterrows():
            line_geo = line_data['geometry']
            line_id = line_data['LIGNE']
            dist = point.distance(line_geo)
            if dist<=closeness_thresh:
                close_not_found = False
                try: 
                    point_line_intersect[line_id][0]+=1
                    point_line_intersect[line_id][1]+=dist
                except Exception as e: 
                    point_line_intersect[line_id] = [1,dist]
        
        if close_not_found:
            far_count+=1
            
        
    far_count_percent = 100 - ((len(df)-far_count)/len(df))*100

    
    # keep top 5 matches
    point_line_intersect = sorted(list(point_line_intersect.items()),key=lambda x:x[1],reverse=True)[:5]
    
    # get points
    ln_ids = []
    avg_d = []
    match_point = []
    for lin,info in point_line_intersect:
        ln_ids.append(lin)
        avg_dist = info[1]/info[0]
        avg_d.append(avg_dist)
        match_point.append(info[0])
        
    
    # normalize data and get prob
    norm_point_match = notmalize_ls(match_point)
    norm_avg_d = 1-notmalize_ls(avg_d)
    prob = (norm_point_match + norm_avg_d)/2
    norm_prob = notmalize_ls(list(prob))
    
    
    combine_info = [[p,q,r,s] for p,q,r,s in zip(ln_ids,match_point,avg_d,norm_prob)]
    trip_track[track_id] = {'line_details':combine_info,'line_unmatch':far_count_percent}

Processing trackID  1
Processing trackID  3
Processing trackID  4
Processing trackID  5
Processing trackID  6
Processing trackID  7
Processing trackID  8
Processing trackID  10
Processing trackID  11


In [ ]:
map_dict = {'b':'bus','t':'tramp','m':'metro'}

In [ ]:
trip_track

{1: {'line_details': [['046b', 48, 5.190929978694064, 0.5936860242726625],
   ['218b', 48, 5.190929978694064, 0.5936860242726625],
   ['002m', 15, 11.528209030689645, 0.2505349787689445],
   ['006m', 15, 11.528209030689645, 0.2505349787689445],
   ['058b', 15, 4.6122426959086456, 0.41175023739292305]],
  'line_unmatch': 58.42696629213483},
 3: {'line_details': [['032t', 110, 6.08421025381108, 0.5126008791937318],
   ['082t', 110, 6.08421025381108, 0.5126008791937318],
   ['049b', 108, 8.479130013288614, 0.45129104693588823],
   ['050b', 108, 8.479130013288614, 0.45129104693588823],
   ['048b', 41, 10.953245688402724, 0.25913984489199304]],
  'line_unmatch': 3.4782608695652186},
 4: {'line_details': [['050b', 241, 5.4445479247599655, 0.5850637117215357],
   ['212b', 125, 6.183511657775444, 0.40982001746009245],
   ['097t', 124, 6.419106683274784, 0.4007728120813934],
   ['032t', 124, 6.2702908919472575, 0.40566560096463783],
   ['082t', 124, 6.2702908919472575, 0.40566560096463783]],
  

In [ ]:
pred_result_df = []
for ID,data in trip_track.items():
    top_n = 4
    id_result = []
    mode = 'other'
    if data['line_unmatch'] > 50:
        top_n-=1
        id_result.append([ID,'other',0,1.0,'other'])
    # if unmatch percent is greater than 50 it means the mode is not on line id so other mode
    for row in data['line_details'][:top_n]:
        id_result.append([ID,row[0],row[1],row[-1],map_dict[row[0][-1]]])
    
    pred_result_df.append(pd.DataFrame(id_result,columns=['track_id','line_id','Points matched No.','probability','class']))   
    #print('mode of track ID {} -> {}'.format(ID,mode))

# RESULTS

In [ ]:
for df in pred_result_df:
    track_id = df['track_id'][0]
    print('Track id - ',track_id)
    print('line unmatch percent',trip_track[track_id]['line_unmatch'])
    display(HTML(df.to_html()))
    print("\n")

Track id -  1
line unmatch percent 58.42696629213483




Track id -  3
line unmatch percent 3.4782608695652186




Track id -  4
line unmatch percent 0.0




Track id -  5
line unmatch percent 0.45871559633027914




Track id -  6
line unmatch percent 15.523465703971112




Track id -  7
line unmatch percent 0.0




Track id -  8
line unmatch percent 64.01273885350318




Track id -  10
line unmatch percent 12.903225806451616




Track id -  11
line unmatch percent 0.4784688995215305


In [ ]:
# colors to choose
color=['red', 'orange', 'yellow', 'green', 'blue', 'purple','lime','indigo', 'cyan']
# draw on each plot
count=0
for ID, data in gps_track.groupby(["TrackId"]):

    df  = pred_result_df[count]
    txt = str(df)
    txt = txt.split("\n")
    count+=1

    gmap = gmplot.GoogleMapPlotter(50.85045,4.34878, 14,apikey='AIzaSyAY0mkNh_DBbiTnI3BAjUaQNEZaHOOMGfc')    
    lat = list(data['lat'])
    lon = list(data['lon'])
    l = len(lat)
    c = color[ID%len(color)]
    gmap.text(lat[l//2], lon[l//2],txt[1],color='black',size =10)
    gmap.text(lat[l//3], lon[l//3],txt[2],color='black',size =10)
    gmap.text(lat[l//4], lon[l//4],txt[3],color='black',size =10)
    gmap.text(lat[l//5], lon[l//5],txt[4],color='black',size =10)
    #gmap.text(lat[-1], lon[-1], str(ID),color='black',size = 10)
    gmap.scatter(lat, lon, color=c, size=4, marker=False)
    gmap.plot(lat,lon, color=c,edgewidth=2.5)
    gmap.draw("/content/drive/MyDrive/data_mining/dataset/task4/TRACK_PLOTS/"+str(ID)+".html")

In [ ]:
str(pred_result_df[0])

'   track_id line_id  Points matched No.  probability  class\n0         1   other                   0     1.000000  other\n1         1    046b                  48     0.593686    bus\n2         1    218b                  48     0.593686    bus\n3         1    002m                  15     0.250535  metro'

In [ ]:
def stats_Calculator(data):        
        mini = np.min(data)*3.6
        maxi = np.max(data)*3.6
        mean = np.mean(data)*3.6
        median = np.median(data)*3.6
        std = np.std(data)*3.6
        x_25 = np.percentile(data, 25)*3.6
        x_50 = np.percentile(data, 50)*3.6
        x_75 = np.percentile(data, 75)*3.6
        
        return [mini, maxi, mean, median,std, x_25,x_50,x_75]

In [ ]:
def get_time(tz_time):
    FMT = "%H:%M:%S"
    tdelta = datetime.strptime(tz_time.split("T")[-1].replace("Z","").split(".")[0], FMT)
    return tdelta

In [ ]:
for ID,df in gps_track_transformed.groupby(['TrackId']):
    print("Processing trackID ",ID)
    track_id = ID
    
    # get speed
    lineStringObj = LineString([[a.x, a.y] for a in df['geometry'].values])
    
    top_row_index = df.head(1).index[0]

    prv_time = get_time(df['time'][top_row_index])
    prv_point = loads(str(df['geometry'][top_row_index]))               
    prv_distance_along_track = 0
    prv_speed = 0
    
    # save stats in list
    dist = []
    speed_ls = []
    acceleration = []
    time = []
        
        
    for index,data in df.iterrows():
        curr_time = get_time(df['time'][index])
        current_point = loads(str(df['geometry'][index]))
        curr_distance_along_track = lineStringObj.project(current_point)

        dist_diff = curr_distance_along_track-prv_distance_along_track
        dist.append(dist_diff)


        # time calculation
        time_diff = (curr_time-prv_time).seconds
        # saftey check
        if time_diff==0:
            time_diff=1
        time.append(time_diff)


        #speed calculation
        speed = (dist_diff/time_diff)
        speed_ls.append(speed)
#         if ID==10:
#             print(index,dist_diff,time_diff)


        # acceleration calculation
        acc = (speed-prv_speed)/time_diff
        acceleration.append(acc)
        

        # update previous values
        prv_time = curr_time
        prv_distance_along_track = curr_distance_along_track
        prv_speed = speed
            
        
    # calculate stats
    #dist_stats = stats_Calculator(dist)
    speed_stats = stats_Calculator(speed_ls)
    acc_stats = stats_Calculator(acceleration)
    time_stats = stats_Calculator(time)

    # saving data to trips_track
    trip_track[ID]['speed_stats'] =  speed_stats
    trip_track[ID]['acc_stats'] =  acc_stats

Processing trackID  1
Processing trackID  3
Processing trackID  4
Processing trackID  5
Processing trackID  6
Processing trackID  7
Processing trackID  8
Processing trackID  10
Processing trackID  11


In [ ]:
test_data = []
for ID,dic in trip_track.items():
    track_id_data = []
    track_id_data.append(2)
    track_id_data = track_id_data + dic['speed_stats'] + dic['acc_stats']
    #track_id_data = track_id_data + dic['speed_stats']
    test_data.append(track_id_data)

In [ ]:
trip_track

{1: {'acc_stats': [-4.4392246081560875,
   9.779263107341396,
   0.3869057123114489,
   -0.03546723145425254,
   2.1988832692495097,
   -0.9300415347038754,
   -0.03546723145425254,
   1.1705955468322964],
  'line_details': [['046b', 48, 5.190929978694064, 0.5936860242726625],
   ['218b', 48, 5.190929978694064, 0.5936860242726625],
   ['002m', 15, 11.528209030689645, 0.2505349787689445],
   ['006m', 15, 11.528209030689645, 0.2505349787689445],
   ['058b', 15, 4.6122426959086456, 0.41175023739292305]],
  'line_unmatch': 58.42696629213483,
  'speed_stats': [7.301994737418361e-11,
   37.879246286242186,
   16.52870591277587,
   16.664805794331915,
   8.858482720878307,
   9.417170900787415,
   16.664805794331915,
   23.688258309010347]},
 3: {'acc_stats': [-17.98778693138927,
   23.371274738418812,
   0.2795180080456341,
   0.013257545518919755,
   4.255351724598487,
   -1.660470809656647,
   0.013257545518919755,
   1.8177609363477307],
  'line_details': [['032t', 110, 6.08421025381108, 

# loading and predicting 

In [ ]:
# and later you can load it
with open('/content/drive/MyDrive/data_mining/dataset/task4/RF.pkl', 'rb') as f:
    clf = pickle.load(f)

In [ ]:
k = [1,3,4,5,6,7,8,10,11]

In [ ]:
np.array(test_data[0])

array([ 2.00000000e+00,  7.30199474e-11,  3.78792463e+01,  1.65287059e+01,
        1.66648058e+01,  8.85848272e+00,  9.41717090e+00,  1.66648058e+01,
        2.36882583e+01, -4.43922461e+00,  9.77926311e+00,  3.86905712e-01,
       -3.54672315e-02,  2.19888327e+00, -9.30041535e-01, -3.54672315e-02,
        1.17059555e+00])

In [ ]:
print('  metro','bus','tramp')
temp = []
for l in test_data:
    print(clf.predict_proba(np.array(l).reshape(1, -1)))
    temp.append(list(clf.predict_proba(np.array(l).reshape(1, -1))))

  metro bus tramp
[[0.04310345 0.42241379 0.53448276]]
[[0.20175439 0.48245614 0.31578947]]
[[0.07017544 0.48245614 0.44736842]]
[[0.0625     0.48214286 0.45535714]]
[[0.08181818 0.44545455 0.47272727]]
[[0.05154639 0.54639175 0.40206186]]
[[0.06086957 0.51304348 0.42608696]]
[[0.23636364 0.41818182 0.34545455]]
[[0.05681818 0.51136364 0.43181818]]


In [ ]:
t = []
for i,p in enumerate(temp):
  s = [k[i]] + list(p[0])
  t.append(s)

In [ ]:
pd.DataFrame(t, columns = ['TrackID','metro','bus','tramp'])

TrackID     metro       bus     tramp
0        1  0.043103  0.422414  0.534483
1        3  0.201754  0.482456  0.315789
2        4  0.070175  0.482456  0.447368
3        5  0.062500  0.482143  0.455357
4        6  0.081818  0.445455  0.472727
5        7  0.051546  0.546392  0.402062
6        8  0.060870  0.513043  0.426087
7       10  0.236364  0.418182  0.345455
8       11  0.056818  0.511364  0.431818